services:
  pgsql:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: alvras
      POSTGRES_USER: alvras_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - alvras-pgsql-data:/var/lib/postgresql/data
    networks:
      - alvras-network

networks:
  alvras-network:
    driver: bridge

volumes:
  alvras-pgsql-data:
